/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyncIndexRouteImport } from './routes/sync.index'
import { Route as SyncIntegrationIdRouteImport } from './routes/sync.$integrationId'
import { Route as SyncIntegrationIdSettingsRouteImport } from './routes/sync_.$integrationId.settings'

const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIndexRoute = SyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIntegrationIdRoute = SyncIntegrationIdRouteImport.update({
  id: '/sync/$integrationId',
  path: '/sync/$integrationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIntegrationIdSettingsRoute =
  SyncIntegrationIdSettingsRouteImport.update({
    id: '/sync_/$integrationId/settings',
    path: '/sync/$integrationId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/sync/$integrationId': typeof SyncIntegrationIdRoute
  '/sync/': typeof SyncIndexRoute
  '/sync/$integrationId/settings': typeof SyncIntegrationIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/sync/$integrationId': typeof SyncIntegrationIdRoute
  '/sync': typeof SyncIndexRoute
  '/sync/$integrationId/settings': typeof SyncIntegrationIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/sync/$integrationId': typeof SyncIntegrationIdRoute
  '/sync/': typeof SyncIndexRoute
  '/sync_/$integrationId/settings': typeof SyncIntegrationIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modules'
    | '/sync/$integrationId'
    | '/sync/'
    | '/sync/$integrationId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modules'
    | '/sync/$integrationId'
    | '/sync'
    | '/sync/$integrationId/settings'
  id:
    | '__root__'
    | '/'
    | '/modules'
    | '/sync/$integrationId'
    | '/sync/'
    | '/sync_/$integrationId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesRoute: typeof ModulesRoute
  SyncIntegrationIdRoute: typeof SyncIntegrationIdRoute
  SyncIndexRoute: typeof SyncIndexRoute
  SyncIntegrationIdSettingsRoute: typeof SyncIntegrationIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/': {
      id: '/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof SyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/$integrationId': {
      id: '/sync/$integrationId'
      path: '/sync/$integrationId'
      fullPath: '/sync/$integrationId'
      preLoaderRoute: typeof SyncIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync_/$integrationId/settings': {
      id: '/sync_/$integrationId/settings'
      path: '/sync/$integrationId/settings'
      fullPath: '/sync/$integrationId/settings'
      preLoaderRoute: typeof SyncIntegrationIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesRoute: ModulesRoute,
  SyncIntegrationIdRoute: SyncIntegrationIdRoute,
  SyncIndexRoute: SyncIndexRoute,
  SyncIntegrationIdSettingsRoute: SyncIntegrationIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
