/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyncIndexRouteImport } from './routes/sync.index'
import { Route as SyncIntegrationIdRouteImport } from './routes/sync.$integrationId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIndexRoute = SyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIntegrationIdRoute = SyncIntegrationIdRouteImport.update({
  id: '/sync/$integrationId',
  path: '/sync/$integrationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/settings': typeof SettingsRoute
  '/sync/$integrationId': typeof SyncIntegrationIdRoute
  '/sync/': typeof SyncIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/settings': typeof SettingsRoute
  '/sync/$integrationId': typeof SyncIntegrationIdRoute
  '/sync': typeof SyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/settings': typeof SettingsRoute
  '/sync/$integrationId': typeof SyncIntegrationIdRoute
  '/sync/': typeof SyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules' | '/settings' | '/sync/$integrationId' | '/sync/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules' | '/settings' | '/sync/$integrationId' | '/sync'
  id:
    | '__root__'
    | '/'
    | '/modules'
    | '/settings'
    | '/sync/$integrationId'
    | '/sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesRoute: typeof ModulesRoute
  SettingsRoute: typeof SettingsRoute
  SyncIntegrationIdRoute: typeof SyncIntegrationIdRoute
  SyncIndexRoute: typeof SyncIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/': {
      id: '/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof SyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/$integrationId': {
      id: '/sync/$integrationId'
      path: '/sync/$integrationId'
      fullPath: '/sync/$integrationId'
      preLoaderRoute: typeof SyncIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesRoute: ModulesRoute,
  SettingsRoute: SettingsRoute,
  SyncIntegrationIdRoute: SyncIntegrationIdRoute,
  SyncIndexRoute: SyncIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
